---
- name: Install Helm (if not already present)
  ansible.builtin.shell: "curl -fsSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash"
  changed_when: false
- name: Add EKS Helm repo
  ansible.builtin.shell: helm repo add eks https://aws.github.io/eks-charts
  changed_when: false
- name: Update Helm repos
  ansible.builtin.shell: helm repo update
  changed_when: false
- name: Install AWS Load Balancer Controller
  kubernetes.core.helm:
    chart_ref: eks/aws-load-balancer-controller
    create_namespace: false
    name: aws-load-balancer-controller
    release_namespace: kube-system
    update_repo_cache: true
    values:
      clusterName: "{{ CLUSTER_NAME }}"
      region: "{{ CLUSTER_REGION }}"
