---
- name: Install Helm
  ansible.builtin.shell: "curl -fsSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash"
  changed_when: false
- name: Add ArgoCD Helm repo
  ansible.builtin.shell: helm repo add argo https://argoproj.github.io/argo-helm
  changed_when: false
- name: Install ArgoCD
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    create_namespace: true
    release_namespace: argocd
    state: present
