---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-actions-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/{{ REPOSITORY_URI }}.git
    path: clusters/eks-cluster
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
