---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: eks-actions-demo
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/eks-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
